//
//  Country.swift
//  TrendingEvent
//
//  Created by Luong Ngoc Thuyet on 6/30/21.
//  Copyright © 2021 thuyetln. All rights reserved.
//

import Foundation
struct Country {
    let name: String
    let alpha2: String
    let image: String
}
let allCountries: [Country] = [
        Country(name: "Afghanistan", alpha2: "AF", image: "af"),
        Country(name: "Åland Islands", alpha2: "AX", image: "ax"),
        Country(name: "Albania", alpha2: "AL", image: "al"),
        Country(name: "Algeria", alpha2: "DZ", image: "dz"),
        Country(name: "American Samoa", alpha2: "AS", image: "as"),
        Country(name: "Andorra", alpha2: "AD", image: "ad"),
        Country(name: "Angola", alpha2: "AO", image: "ao"),
        Country(name: "Anguilla", alpha2: "AI", image: "ai"),
        Country(name: "Antarctica", alpha2: "AQ", image: "aq"),
        Country(name: "Antigua and Barbuda", alpha2: "AG", image: "ag"),
        Country(name: "Argentina", alpha2: "AR", image: "ar"),
        Country(name: "Armenia", alpha2: "AM", image: "am"),
        Country(name: "Aruba", alpha2: "AW", image: "aw"),
        Country(name: "Australia", alpha2: "AU", image: "au"),
        Country(name: "Austria", alpha2: "AT", image: "at"),
        Country(name: "Azerbaijan", alpha2: "AZ", image: "az"),
        Country(name: "Bahamas", alpha2: "BS", image: "bs"),
        Country(name: "Bahrain", alpha2: "BH", image: "bh"),
        Country(name: "Bangladesh", alpha2: "BD", image: "bd"),
        Country(name: "Barbados", alpha2: "BB", image: "bb"),
        Country(name: "Belarus", alpha2: "BY", image: "by"),
        Country(name: "Belgium", alpha2: "BE", image: "be"),
        Country(name: "Belize", alpha2: "BZ", image: "bz"),
        Country(name: "Benin", alpha2: "BJ", image: "bj"),
        Country(name: "Bermuda", alpha2: "BM", image: "bm"),
        Country(name: "Bhutan", alpha2: "BT", image: "bt"),
        Country(name: "Bolivia, Plurinational State of", alpha2: "BO", image: "bo"),
        Country(name: "Bonaire, Sint Eustatius and Saba", alpha2: "BQ", image: "bq"),
        Country(name: "Bosnia and Herzegovina", alpha2: "BA", image: "ba"),
        Country(name: "Botswana", alpha2: "BW", image: "bw"),
        Country(name: "Bouvet Island", alpha2: "BV", image: "bv"),
        Country(name: "Brazil", alpha2: "BR", image: "br"),
        Country(name: "British Indian Ocean Territory", alpha2: "IO", image: "io"),
        Country(name: "Brunei Darussalam", alpha2: "BN", image: "bn"),
        Country(name: "Bulgaria", alpha2: "BG", image: "bg"),
        Country(name: "Burkina Faso", alpha2: "BF", image: "bf"),
        Country(name: "Burundi", alpha2: "BI", image: "bi"),
        Country(name: "Cambodia", alpha2: "KH", image: "kh"),
        Country(name: "Cameroon", alpha2: "CM", image: "cm"),
        Country(name: "Canada", alpha2: "CA", image: "ca"),
        Country(name: "Cabo Verde", alpha2: "CV", image: "cv"),
        Country(name: "Cayman Islands", alpha2: "KY", image: "ky"),
        Country(name: "Central African Republic", alpha2: "CF", image: "cf"),
        Country(name: "Chad", alpha2: "TD", image: "td"),
        Country(name: "Chile", alpha2: "CL", image: "cl"),
        Country(name: "China", alpha2: "CN", image: "cn"),
        Country(name: "Christmas Island", alpha2: "CX", image: "cx"),
        Country(name: "Cocos (Keeling) Islands", alpha2: "CC", image: "cc"),
        Country(name: "Colombia", alpha2: "CO", image: "co"),
        Country(name: "Comoros", alpha2: "KM", image: "km"),
        Country(name: "Congo", alpha2: "CG", image: "cg"),
        Country(name: "Congo, the Democratic Republic of the", alpha2: "CD", image: "cd"),
        Country(name: "Cook Islands", alpha2: "CK", image: "ck"),
        Country(name: "Costa Rica", alpha2: "CR", image: "cr"),
        Country(name: "Côte d'Ivoire", alpha2: "CI", image: "ci"),
        Country(name: "Croatia", alpha2: "HR", image: "hr"),
        Country(name: "Cuba", alpha2: "CU", image: "cu"),
        Country(name: "Curaçao", alpha2: "CW", image: "cw"),
        Country(name: "Cyprus", alpha2: "CY", image: "cy"),
        Country(name: "Czech Republic", alpha2: "CZ", image: "cz"),
        Country(name: "Denmark", alpha2: "DK", image: "dk"),
        Country(name: "Djibouti", alpha2: "DJ", image: "dj"),
        Country(name: "Dominica", alpha2: "DM", image: "dm"),
        Country(name: "Dominican Republic", alpha2: "DO", image: "do"),
        Country(name: "Ecuador", alpha2: "EC", image: "ec"),
        Country(name: "Egypt", alpha2: "EG", image: "eg"),
        Country(name: "El Salvador", alpha2: "SV", image: "sv"),
        Country(name: "Equatorial Guinea", alpha2: "GQ", image: "gq"),
        Country(name: "Eritrea", alpha2: "ER", image: "er"),
        Country(name: "Estonia", alpha2: "EE", image: "ee"),
        Country(name: "Ethiopia", alpha2: "ET", image: "et"),
        Country(name: "Falkland Islands (Malvinas)", alpha2: "FK", image: "fk"),
        Country(name: "Faroe Islands", alpha2: "FO", image: "fo"),
        Country(name: "Fiji", alpha2: "FJ", image: "fj"),
        Country(name: "Finland", alpha2: "FI", image: "fi"),
        Country(name: "France", alpha2: "FR", image: "fr"),
        Country(name: "French Guiana", alpha2: "GF", image: "gf"),
        Country(name: "French Polynesia", alpha2: "PF", image: "pf"),
        Country(name: "French Southern Territories", alpha2: "TF", image: "tf"),
        Country(name: "Gabon", alpha2: "GA", image: "ga"),
        Country(name: "Gambia", alpha2: "GM", image: "gm"),
        Country(name: "Georgia", alpha2: "GE", image: "ge"),
        Country(name: "Germany", alpha2: "DE", image: "de"),
        Country(name: "Ghana", alpha2: "GH", image: "gh"),
        Country(name: "Gibraltar", alpha2: "GI", image: "gi"),
        Country(name: "Greece", alpha2: "GR", image: "gr"),
        Country(name: "Greenland", alpha2: "GL", image: "gl"),
        Country(name: "Grenada", alpha2: "GD", image: "gd"),
        Country(name: "Guadeloupe", alpha2: "GP", image: "gp"),
        Country(name: "Guam", alpha2: "GU", image: "gu"),
        Country(name: "Guatemala", alpha2: "GT", image: "gt"),
        Country(name: "Guernsey", alpha2: "GG", image: "gg"),
        Country(name: "Guinea", alpha2: "GN", image: "gn"),
        Country(name: "Guinea-Bissau", alpha2: "GW", image: "gw"),
        Country(name: "Guyana", alpha2: "GY", image: "gy"),
        Country(name: "Haiti", alpha2: "HT", image: "ht"),
        Country(name: "Heard Island and McDonald Islands", alpha2: "HM", image: "hm"),
        Country(name: "Holy See (Vatican City State)", alpha2: "VA", image: "va"),
        Country(name: "Honduras", alpha2: "HN", image: "hn"),
        Country(name: "Hong Kong", alpha2: "HK", image: "hk"),
        Country(name: "Hungary", alpha2: "HU", image: "hu"),
        Country(name: "Iceland", alpha2: "IS", image: "is"),
        Country(name: "India", alpha2: "IN", image: "in"),
        Country(name: "Indonesia", alpha2: "ID", image: "id"),
        Country(name: "Iran, Islamic Republic of", alpha2: "IR", image: "ir"),
        Country(name: "Iraq", alpha2: "IQ", image: "iq"),
        Country(name: "Ireland", alpha2: "IE", image: "ie"),
        Country(name: "Isle of Man", alpha2: "IM", image: "im"),
        Country(name: "Israel", alpha2: "IL", image: "il"),
        Country(name: "Italy", alpha2: "IT", image: "it"),
        Country(name: "Jamaica", alpha2: "JM", image: "jm"),
        Country(name: "Japan", alpha2: "JP", image: "jp"),
        Country(name: "Jersey", alpha2: "JE", image: "je"),
        Country(name: "Jordan", alpha2: "JO", image: "jo"),
        Country(name: "Kazakhstan", alpha2: "KZ", image: "kz"),
        Country(name: "Kenya", alpha2: "KE", image: "ke"),
        Country(name: "Kiribati", alpha2: "KI", image: "ki"),
        Country(name: "Korea, Democratic People's Republic of", alpha2: "KP", image: "kp"),
        Country(name: "Korea, Republic of", alpha2: "KR", image: "kr"),
        Country(name: "Kuwait", alpha2: "KW", image: "kw"),
        Country(name: "Kyrgyzstan", alpha2: "KG", image: "kg"),
        Country(name: "Lao People's Democratic Republic", alpha2: "LA", image: "la"),
        Country(name: "Latvia", alpha2: "LV", image: "lv"),
        Country(name: "Lebanon", alpha2: "LB", image: "lb"),
        Country(name: "Lesotho", alpha2: "LS", image: "ls"),
        Country(name: "Liberia", alpha2: "LR", image: "lr"),
        Country(name: "Libya", alpha2: "LY", image: "ly"),
        Country(name: "Liechtenstein", alpha2: "LI", image: "li"),
        Country(name: "Lithuania", alpha2: "LT", image: "lt"),
        Country(name: "Luxembourg", alpha2: "LU", image: "lu"),
        Country(name: "Macao", alpha2: "MO", image: "mo"),
        Country(name: "Macedonia, the former Yugoslav Republic of", alpha2: "MK", image: "mk"),
        Country(name: "Madagascar", alpha2: "MG", image: "mg"),
        Country(name: "Malawi", alpha2: "MW", image: "mw"),
        Country(name: "Malaysia", alpha2: "MY", image: "my"),
        Country(name: "Maldives", alpha2: "MV", image: "mv"),
        Country(name: "Mali", alpha2: "ML", image: "ml"),
        Country(name: "Malta", alpha2: "MT", image: "mt"),
        Country(name: "Marshall Islands", alpha2: "MH", image: "mh"),
        Country(name: "Martinique", alpha2: "MQ", image: "mq"),
        Country(name: "Mauritania", alpha2: "MR", image: "mr"),
        Country(name: "Mauritius", alpha2: "MU", image: "mu"),
        Country(name: "Mayotte", alpha2: "YT", image: "yt"),
        Country(name: "Mexico", alpha2: "MX", image: "mx"),
        Country(name: "Micronesia, Federated States of", alpha2: "FM", image: "fm"),
        Country(name: "Moldova, Republic of", alpha2: "MD", image: "md"),
        Country(name: "Monaco", alpha2: "MC", image: "mc"),
        Country(name: "Mongolia", alpha2: "MN", image: "mn"),
        Country(name: "Montenegro", alpha2: "ME", image: "me"),
        Country(name: "Montserrat", alpha2: "MS", image: "ms"),
        Country(name: "Morocco", alpha2: "MA", image: "ma"),
        Country(name: "Mozambique", alpha2: "MZ", image: "mz"),
        Country(name: "Myanmar", alpha2: "MM", image: "mm"),
        Country(name: "Namibia", alpha2: "NA", image: "na"),
        Country(name: "Nauru", alpha2: "NR", image: "nr"),
        Country(name: "Nepal", alpha2: "NP", image: "np"),
        Country(name: "Netherlands", alpha2: "NL", image: "nl"),
        Country(name: "New Caledonia", alpha2: "NC", image: "nc"),
        Country(name: "New Zealand", alpha2: "NZ", image: "nz"),
        Country(name: "Nicaragua", alpha2: "NI", image: "ni"),
        Country(name: "Niger", alpha2: "NE", image: "ne"),
        Country(name: "Nigeria", alpha2: "NG", image: "ng"),
        Country(name: "Niue", alpha2: "NU", image: "nu"),
        Country(name: "Norfolk Island", alpha2: "NF", image: "nf"),
        Country(name: "Northern Mariana Islands", alpha2: "MP", image: "mp"),
        Country(name: "Norway", alpha2: "NO", image: "no"),
        Country(name: "Oman", alpha2: "OM", image: "om"),
        Country(name: "Pakistan", alpha2: "PK", image: "pk"),
        Country(name: "Palau", alpha2: "PW", image: "pw"),
        Country(name: "Palestine, State of", alpha2: "PS", image: "ps"),
        Country(name: "Panama", alpha2: "PA", image: "pa"),
        Country(name: "Papua New Guinea", alpha2: "PG", image: "pg"),
        Country(name: "Paraguay", alpha2: "PY", image: "py"),
        Country(name: "Peru", alpha2: "PE", image: "pe"),
        Country(name: "Philippines", alpha2: "PH", image: "ph"),
        Country(name: "Pitcairn", alpha2: "PN", image: "pn"),
        Country(name: "Poland", alpha2: "PL", image: "pl"),
        Country(name: "Portugal", alpha2: "PT", image: "pt"),
        Country(name: "Puerto Rico", alpha2: "PR", image: "pr"),
        Country(name: "Qatar", alpha2: "QA", image: "qa"),
        Country(name: "Réunion", alpha2: "RE", image: "re"),
        Country(name: "Romania", alpha2: "RO", image: "ro"),
        Country(name: "Russian Federation", alpha2: "RU", image: "ru"),
        Country(name: "Rwanda", alpha2: "RW", image: "rw"),
        Country(name: "Saint Barthélemy", alpha2: "BL", image: "bl"),
        Country(name: "Saint Helena, Ascension and Tristan da Cunha", alpha2: "SH", image: "sh"),
        Country(name: "Saint Kitts and Nevis", alpha2: "KN", image: "kn"),
        Country(name: "Saint Lucia", alpha2: "LC", image: "lc"),
        Country(name: "Saint Martin (French part)", alpha2: "MF", image: "mf"),
        Country(name: "Saint Pierre and Miquelon", alpha2: "PM", image: "pm"),
        Country(name: "Saint Vincent and the Grenadines", alpha2: "VC", image: "vc"),
        Country(name: "Samoa", alpha2: "WS", image: "ws"),
        Country(name: "San Marino", alpha2: "SM", image: "sm"),
        Country(name: "Sao Tome and Principe", alpha2: "ST", image: "st"),
        Country(name: "Saudi Arabia", alpha2: "SA", image: "sa"),
        Country(name: "Senegal", alpha2: "SN", image: "sn"),
        Country(name: "Serbia", alpha2: "RS", image: "rs"),
        Country(name: "Seychelles", alpha2: "SC", image: "sc"),
        Country(name: "Sierra Leone", alpha2: "SL", image: "sl"),
        Country(name: "Singapore", alpha2: "SG", image: "sg"),
        Country(name: "Sint Maarten (Dutch part)", alpha2: "SX", image: "sx"),
        Country(name: "Slovakia", alpha2: "SK", image: "sk"),
        Country(name: "Slovenia", alpha2: "SI", image: "si"),
        Country(name: "Solomon Islands", alpha2: "SB", image: "sb"),
        Country(name: "Somalia", alpha2: "SO", image: "so"),
        Country(name: "South Africa", alpha2: "ZA", image: "za"),
        Country(name: "South Georgia and the South Sandwich Islands", alpha2: "GS", image: "gs"),
        Country(name: "South Sudan", alpha2: "SS", image: "ss"),
        Country(name: "Spain", alpha2: "ES", image: "es"),
        Country(name: "Sri Lanka", alpha2: "LK", image: "lk"),
        Country(name: "Sudan", alpha2: "SD", image: "sd"),
        Country(name: "Suriname", alpha2: "SR", image: "sr"),
        Country(name: "Svalbard and Jan Mayen", alpha2: "SJ", image: "sj"),
        Country(name: "Swaziland", alpha2: "SZ", image: "sz"),
        Country(name: "Sweden", alpha2: "SE", image: "se"),
        Country(name: "Switzerland", alpha2: "CH", image: "ch"),
        Country(name: "Syrian Arab Republic", alpha2: "SY", image: "sy"),
        Country(name: "Taiwan, Province of China", alpha2: "TW", image: "tw"),
        Country(name: "Tajikistan", alpha2: "TJ", image: "tj"),
        Country(name: "Tanzania, United Republic of", alpha2: "TZ", image: "tz"),
        Country(name: "Thailand", alpha2: "TH", image: "th"),
        Country(name: "Timor-Leste", alpha2: "TL", image: "tl"),
        Country(name: "Togo", alpha2: "TG", image: "tg"),
        Country(name: "Tokelau", alpha2: "TK", image: "tk"),
        Country(name: "Tonga", alpha2: "TO", image: "to"),
        Country(name: "Trinidad and Tobago", alpha2: "TT", image: "tt"),
        Country(name: "Tunisia", alpha2: "TN", image: "tn"),
        Country(name: "Turkey", alpha2: "TR", image: "tr"),
        Country(name: "Turkmenistan", alpha2: "TM", image: "tm"),
        Country(name: "Turks and Caicos Islands", alpha2: "TC", image: "tc"),
        Country(name: "Tuvalu", alpha2: "TV", image: "tv"),
        Country(name: "Uganda", alpha2: "UG", image: "ug"),
        Country(name: "Ukraine", alpha2: "UA", image: "ua"),
        Country(name: "United Arab Emirates", alpha2: "AE", image: "ae"),
        Country(name: "United Kingdom", alpha2: "GB", image: "gb"),
        Country(name: "United States", alpha2: "US", image: "us"),
        Country(name: "United States Minor Outlying Islands", alpha2: "UM", image: "um"),
        Country(name: "Uruguay", alpha2: "UY", image: "uy"),
        Country(name: "Uzbekistan", alpha2: "UZ", image: "uz"),
        Country(name: "Vanuatu", alpha2: "VU", image: "vu"),
        Country(name: "Venezuela, Bolivarian Republic of", alpha2: "VE", image: "ve"),
        Country(name: "Vietnam", alpha2: "VN", image: "vn"),
        Country(name: "Virgin Islands, British", alpha2: "VG", image: "vg"),
        Country(name: "Virgin Islands, U.S.", alpha2: "VI", image: "vi"),
        Country(name: "Wallis and Futuna", alpha2: "WF", image: "wf"),
        Country(name: "Western Sahara", alpha2: "EH", image: "eh"),
        Country(name: "Yemen", alpha2: "YE", image: "ye"),
        Country(name: "Zambia", alpha2: "ZM", image: "zm"),
        Country(name: "Zimbabwe", alpha2: "ZW", image: "zw")
]
    // swiftlint:enable line_length
